name: Update My Stats!
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: ["main"]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: 'main'